//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_search
    {
        public int histSearchId { get; set; }
        public int userId { get; set; }
        public string locationId { get; set; }
        public int mont { get; set; }
        public int year { get; set; }
    }
}
